# Generated by Django 2.1.4 on 2019-02-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190220_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='picture',
            new_name='post_picture',
        ),
        migrations.AddField(
            model_name='post',
            name='title_picture',
            field=models.ImageField(blank=True, max_length=60, upload_to='images/blog/'),
        ),
    ]
