# Generated by Django 2.1.4 on 2019-02-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link_url',
            field=models.URLField(blank=True),
        ),
    ]
