# Generated by Django 2.1.4 on 2019-02-23 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190223_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='registered',
            new_name='registered_on',
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
