# Generated by Django 2.1.4 on 2019-02-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190223_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sub_title',
        ),
        migrations.AlterField(
            model_name='picture',
            name='caption',
            field=models.CharField(max_length=100),
        ),
    ]
