# Generated by Django 3.1.3 on 2020-11-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190225_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_picture',
            field=models.ImageField(max_length=60, upload_to='images/blog/'),
        ),
    ]
